name: rickandmorty
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter

  # https://pub.dev/packages/lazy_load_scrollview/install
  lazy_load_scrollview: ^1.3.0

  shared_preferences: ^2.0.12

  ###
  ### FONTS
  ###
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
